name: Build

on:
  push:
    branches: [ master ]
    tags-ignore: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Check format
      run: sbt scalafmtCheckAll
    - name: Run tests
      run: sbt test
